Models/McwModel.cs
namespace Redirect_PaymentForm_.NET.Models
{
    public class PaymentRequest
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string OrderId { get; set; }
        public double Amount { get; set; }
        public string Currency { get; set; }
        public string IdentityCode { get; set; }
    }

    public class PaymentResponse
    {
        public Dictionary<string, string> Parameters { get; set; }
        public string PrettyJson { get; set; }
    }
}

Controllers/McwController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using Redirect_PaymentForm_.NET.Services;
using Redirect_PaymentForm_.NET.Models;

namespace Redirect_PaymentForm_.NET.Controllers
{
    public class McwController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly McwPayment _mcwPayment;

        public McwController(IConfiguration configuration)
        {
            _configuration = configuration;
            _mcwPayment = new McwPayment(configuration);
        }

        // @@ Manejo de solicitudes GET para la ruta raíz @@
        [HttpGet]
        public IActionResult Index()
        {
            string orderId = "Order-" + DateTime.Now.ToString("yyyyMMddHHmmss");
            ViewBag.OrderId = orderId;
            return View();
        }

        // @@ Manejo de solicitudes POST para checkout @@
        [HttpPost("/checkout")]
        public IActionResult Checkout([FromForm] PaymentRequest paymentRequest)
        {
            try
            {
                // Calcular el Signature y los valores dinámicos para el formulario
                var formParams = _mcwPayment.GenerateFormData(paymentRequest);
                // Renderiza el template
                return View("Checkout", formParams);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        // @@ Manejo de solicitudes POST para result @@
        [HttpPost("/result")]
        public IActionResult Result([FromForm] IFormCollection form)
        {
            if (!form.Any())
                throw new Exception("No post data received!");

            // Válida que la respuesta sea íntegra comparando el signature recibido con el generado
            if (!_mcwPayment.CheckSignature(form))
                throw new Exception("Invalid signature");

            var formData = new PaymentResponse
            {
                // Convierte los datos del formulario en un diccionario de clave-valor
                Parameters = form.ToDictionary(k => k.Key, v => v.Value.ToString()),
                // Convierte los datos a un JSON con indentación legible
                PrettyJson = JsonSerializer.Serialize(
                    form.ToDictionary(k => k.Key, v => v.Value.ToString()),
                    new JsonSerializerOptions { WriteIndented = true }
                )
            };
            // Renderiza el template
            return View("Result", formData);
        }

        // @@ Manejo de solicitudes POST para la ipn @@
        [HttpPost("/ipn")]
        public IActionResult Ipn([FromForm] IFormCollection form)
        {
            if (!form.Any())
                throw new Exception("no post data received!");

            // Válida que la respuesta sea íntegra comparando el signature recibido con el generado
            if (!_mcwPayment.CheckSignature(form))
                throw new Exception("Invalid signature");

            // Almacena algunos datos de la respuesta IPN en variables
            var orderStatus = form["vads_trans_status"].ToString();
            var orderId = form["vads_order_id"].ToString();
            var uuid = form["vads_trans_uuid"].ToString();

            // Retorna en la respuesta el Order Status
            return Ok($"OK! OrderStatus is {orderStatus}");
        }
    }
}

Views/Mcw/Checkout.cshtml
@model Dictionary<string, string>
@{
	ViewData["Title"] = "Checkout";
	var amount = (int.Parse(Model["vads_amount"]) / 100m).ToString("0.00");
	var currency = Model["vads_currency"] == "604" ? "PEN" : "USD";
}

@section extrahead {
}

@section extrastyles {
}

<div class="right-column col-md-6 data-checkout">
    <section class="customer-details">
        <h2>Datos del pago</h2>
        <!-- Order ID -->
        <div class="form-group">
            <label for="orderId">Order-id</label>
            <input readonly class="form-control" name="vads_order_id" value="@Model["vads_order_id"]" />
        </div>
        <!-- Monto -->
        <div class="form-group">
            <label for="amount">Monto</label>
            <input readonly class="form-control" name="amount" value="@amount" />
        </div>
        <!-- Moneda -->
        <div class="form-group">
            <label for="amount">Moneda</label>
            <input readonly class="form-control" name="currency" value="@currency" />
        </div>
    </section>
</div>

<section class="container">
    <!-- Formulario con los datos de pago -->
    <form class="from-checkout" action="https://secure.micuentaweb.pe/vads-payment/" method="post">
        <!-- Inputs generados dinámicamente -->
        <input type="hidden" name="vads_action_mode" value="@Model["vads_action_mode"]" />
        <input type="hidden" name="vads_amount" value="@Model["vads_amount"]" />
        <input type="hidden" name="vads_ctx_mode" value="@Model["vads_ctx_mode"]" />
        <input type="hidden" name="vads_currency" value="@Model["vads_currency"]" />
        <input type="hidden" name="vads_cust_address" value="@Model["vads_cust_address"]" />
        <input type="hidden" name="vads_cust_cell_phone" value="@Model["vads_cust_cell_phone"]" />
        <input type="hidden" name="vads_cust_city" value="@Model["vads_cust_city"]" />
        <input type="hidden" name="vads_cust_country" value="@Model["vads_cust_country"]" />
        <input type="hidden" name="vads_cust_email" value="@Model["vads_cust_email"]" />
        <input type="hidden" name="vads_cust_first_name" value="@Model["vads_cust_first_name"]" />
        <input type="hidden" name="vads_cust_last_name" value="@Model["vads_cust_last_name"]" />
        <input type="hidden" name="vads_cust_state" value="@Model["vads_cust_state"]" />
        <input type="hidden" name="vads_cust_zip" value="@Model["vads_cust_zip"]" />
        <input type="hidden" name="vads_cust_national_id" value="@Model["vads_cust_national_id"]" />
        <input type="hidden" name="vads_order_id" value="@Model["vads_order_id"]" />
        <input type="hidden" name="vads_page_action" value="@Model["vads_page_action"]" />
        <input type="hidden" name="vads_payment_config" value="@Model["vads_payment_config"]" />
        <input type="hidden" name="vads_redirect_success_timeout" value="@Model["vads_redirect_success_timeout"]" />
        <input type="hidden" name="vads_return_mode" value="@Model["vads_return_mode"]" />
        <input type="hidden" name="vads_site_id" value="@Model["vads_site_id"]" />
        <input type="hidden" name="vads_trans_date" value="@Model["vads_trans_date"]" />
        <input type="hidden" name="vads_trans_id" value="@Model["vads_trans_id"]" />
        <input type="hidden" name="vads_url_success" value="@Model["vads_url_success"]" />
        <input type="hidden" name="vads_version" value="@Model["vads_version"]" />
        <input type="hidden" name="signature" value="@Model["signature"]" />

        <button class="btn btn-checkout" type="submit" name="pagar">Pagar</button>
    </form>
</section>

@section extrajs {
    <script>
    </script>
}

Views/Mcw/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@section extrastyles {
}

<section class="container">
    <form id="checkoutForm" action="checkout" class="col-md-12" method="POST">
        <div class="row">
            <div class="left-column col-md-6">
                <section class="customer-details">
                    <h2>Datos del cliente</h2>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="firstName">Nombre</label>
                            <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Nombre" required>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="lastName">Apellido</label>
                            <input type="text" class="form-control" id="lastName" name="lastName" placeholder="Apellido" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="email">Correo Electrónico</label>
                        <input type="email" class="form-control" id="email" name="email" placeholder="Email" required>
                    </div>
                    <div class="form-group">
                        <label for="phoneNumber">Teléfono</label>
                        <input type="tel" class="form-control" id="phoneNumber" name="phoneNumber" placeholder="999999999" required>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="identityType">Tipo de Documento</label>
                            <select class="form-control" id="identityType" name="identityType">
                                <option value="DNI">DNI</option>
                                <option value="PS">Pasaporte</option>
                                <option value="CE">Carné de Extranjería</option>
                            </select>
                        </div>
                        <div class="form-group col-md-8">
                            <label for="identityCode">Documento</label>
                            <input type="text" class="form-control" id="identityCode" name="identityCode" placeholder="Doc. Identidad" required>
                        </div>
                    </div>
                </section>
                <section class="billing-details">
                    <h2>Datos de envío</h2>
                    <div class="form-group">
                        <label for="address">Dirección</label>
                        <input type="text" class="form-control" id="address" name="address" placeholder="Nombre de la calle y número de casa" required>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="country">País</label>
                            <select class="form-control" id="country" name="country">
                                <option value="PE">Perú</option>
                                <option value="AR">Argentina</option>
                                <option value="CL">Chile</option>
                                <option value="CO">Colombia</option>
                            </select>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="state">Departamento</label>
                            <input type="text" class="form-control" id="state" name="state" placeholder="Departamento" required>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="city">Distrito</label>
                            <input type="text" class="form-control" id="city" name="city" placeholder="Distrito" required>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="zipCode">Código Postal</label>
                            <input type="text" class="form-control" id="zipCode" name="zipCode" placeholder="15021" required>
                        </div>
                    </div>
                </section>
            </div>
            <div class="right-column col-md-6">
                <section class="customer-details">
                    <h2>Datos del pago</h2>
                    <div class="form-group">
                        <label for="orderId">Order-id</label>
                        <input type="text" class="form-control" id="orderId" name="orderId" value="@ViewData["OrderId"]" required>
                    </div>
                    <div class="form-group">
                        <label for="amount">Monto</label>
                        <input type="number" class="form-control" id="amount" name="amount" placeholder="0.00" step="0.01" min="0" required>
                    </div>
                    <div class="form-group">
                        <label for="currency">Moneda</label>
                        <select class="form-control" id="currency" name="currency">
                            <option value="604">Soles</option>
                            <option value="840">Dólares</option>
                        </select>
                    </div>
                </section>
                <button class="btn btn-primary" type="submit">Pagar</button>
            </div>
        </div>
    </form>
</section>

@section extrajs {
}

Views/Mcw/Result.cshtml
@using Redirect_PaymentForm_.NET.Models
@model PaymentResponse
@{
    ViewData["Title"] = "Resultado";
    var amount = (int.Parse(Model.Parameters["vads_amount"]) / 100m).ToString("0.00");
    var currency = Model.Parameters["vads_currency"] == "604" ? "PEN" : "USD";
}

<section class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="center-column col-md-6">
            <section class="result-form">
                <h2>Resultado de pago:</h2>
                <hr>
                <p><strong>Estado:</strong> <span>@Model.Parameters["vads_trans_status"]</span></p>
                <p>
                    <strong>Monto:</strong> 
                    <span>@currency</span>
                    <span>@amount</span>
                </p>
                <p><strong>Order-id:</strong> <span>@Model.Parameters["vads_order_id"]</span></p>
                <hr>
                <details>
                    <summary><h2>Respuesta recibida del servidor:</h2></summary>
                    <hr>
                    <pre>@Model.PrettyJson</pre>
                </details>
                <hr>
                <form asp-controller="Mcw" asp-action="Index" method="get">
                    <button class="btn btn-primary">Volver a probar</button>
                </form>
            </section>
        </div>
        <div class="col-md-3"></div>
    </div>
</section>

@section extrajs {
    <script>
    </script>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en-US">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MiCuentaWeb</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@4.5.2/dist/journal/bootstrap.min.css" integrity="sha384-QDSPDoVOoSWz2ypaRUidLmLYl4RyoBWI44iA5agn6jHegBxZkNqgm2eHb6yZ5bYs" crossorigin="anonymous" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    @RenderSection("extrahead", required: false)
    @RenderSection("extrastyles", required: false)
    <style>
        body {
            font: 14px "Lucida Grande", Helvetica, Arial, sans-serif;
            background-color: #ececec !important;
        }

        h2 {
            font-size: 18px !important;
            color: #333;
        }

        li {
            padding-right: 5px;
            font-weight: 700;
            font-family: "News Cycle", "Arial Narrow Bold", sans-serif;
        }

        .container {
            border-radius: 4px;
        }

        .left-column,
        .right-column,
        .center-column {
            flex: 1;
            padding: 20px;
            padding-bottom: 0;
        }

        .customer-details,
        .billing-details,
        .payment-form,
        .result-form {
            background-color: white;
            margin-bottom: 20px;
            padding: 20px;
            border-radius: 4px;
        }

        .left-column,
        .right-column {
            width: 100%;
        }

        }

        .form-group label {
            font-size: 0.8rem;
        }

        .form-control {
            font-size: 0.8rem;
            padding: 5px 10px;
            height: auto;
        }

        .form-group {
            margin-bottom: 10px !important;
        }

        .form-checkout {
            text-align: center;
        }


        .btn-primary {
            width: 100%;
            background-color: #FF2D46 !important;
            height: 50px;
        }

        .btn-checkout {
            display: block;
            width: 30%;
            background-color: #FF2D46 !important;
            color: white;
            height: 50px;
            margin: 50px auto;
        }

        .data-checkout {
            margin: 10px auto !important;
        }

        pre {
            background-color: #000000;
            color: white !important;
        }

        #micuentawebstd_rest_wrapper {
            display: flex;
            justify-content: center;
        }

        details summary h2 {
            display: inline;
            margin: 0;
        }
    </style>
</head>

<body style="background-color: #FF2D46;">
    <main class="main">
        <nav class="navbar bg-primary" style="background-color: #FF2D46!important;">
            <div class="container-fluid">
                <a href="/" class="navbar-brand mb-1">
                    <img src="https://iziweb001b.s3.amazonaws.com/webresources/img/logo.png" width="80" />
                </a>
            </div>
        </nav>
        @RenderBody()
    </main>
    @RenderSection("extrajs", required: false)
</body>

</html>